/**
 * ═══════════════════════════════════════════════════════════════════════════
 * SOUL CODEX - CUSTOM PDF TEMPLATES
 * Generate beautiful PDF reports for profiles
 * ═══════════════════════════════════════════════════════════════════════════
 */

import type { Profile } from '../shared/schema';

export interface PDFOptions {
  template: 'full-profile' | 'summary' | 'compatibility' | 'transits' | 'custom';
  includeSections?: string[];
  theme?: 'mystical' | 'minimal' | 'cosmic' | 'elegant';
  watermark?: boolean;
  customTitle?: string;
}

export interface PDFTemplate {
  title: string;
  sections: PDFSection[];
  footer?: string;
  metadata: {
    generatedAt: Date;
    profileName: string;
    template: string;
  };
}

export interface PDFSection {
  type: 'header' | 'text' | 'list' | 'chart' | 'table' | 'image';
  title?: string;
  content: any;
  style?: Record<string, string>;
}

/**
 * Generate PDF from profile data
 * Note: This is a template structure. In production, use a library like pdfkit or puppeteer
 */
export function generateProfilePDF(
  profile: Profile,
  options: PDFOptions = { template: 'full-profile', theme: 'mystical' }
): PDFTemplate {
  const sections: PDFSection[] = [];

  // Header
  sections.push({
    type: 'header',
    title: options.customTitle || `${profile.name}'s Soul Codex Profile`,
    content: {
      subtitle: 'Engine of the Eternal Now',
      generatedAt: new Date().toLocaleDateString()
    }
  });

  // Profile Overview
  sections.push({
    type: 'text',
    title: 'Profile Overview',
    content: {
      name: profile.name,
      birthDate: profile.birthDate,
      birthLocation: profile.birthLocation
    }
  });

  // Astrology Section
  const astrologyData = profile.astrologyData as any;
  if (astrologyData && shouldIncludeSection('astrology', options.includeSections)) {
    sections.push({
      type: 'text',
      title: 'Astrological Blueprint',
      content: {
        sunSign: astrologyData.sunSign,
        moonSign: astrologyData.moonSign,
        risingSign: astrologyData.risingSign,
        elements: extractElements(astrologyData)
      }
    });
  }

  // Numerology Section
  const numerologyData = profile.numerologyData as any;
  if (numerologyData && shouldIncludeSection('numerology', options.includeSections)) {
    sections.push({
      type: 'text',
      title: 'Numerology',
      content: {
        lifePath: numerologyData.calculateNumerology?.lifePath,
        expression: numerologyData.calculateNumerology?.expression,
        soulUrge: numerologyData.calculateNumerology?.soulUrge
      }
    });
  }

  // Elemental Medicine
  const elementalData = (profile as any).elementalMedicineData;
  if (elementalData && shouldIncludeSection('elemental', options.includeSections)) {
    sections.push({
      type: 'text',
      title: 'Elemental Medicine',
      content: {
        primaryElement: elementalData.primaryElement,
        secondaryElement: elementalData.secondaryElement,
        balance: elementalData.balance,
        interpretation: elementalData.interpretation
      }
    });
  }

  // Moral Compass
  const moralCompassData = (profile as any).moralCompassData;
  if (moralCompassData && shouldIncludeSection('moral-compass', options.includeSections)) {
    sections.push({
      type: 'text',
      title: 'Moral Compass',
      content: {
        compassType: moralCompassData.compassType,
        coreValues: moralCompassData.coreValues,
        ethicalFramework: moralCompassData.ethicalFramework
      }
    });
  }

  // Parental Influence
  const parentalData = (profile as any).parentalInfluenceData;
  if (parentalData && shouldIncludeSection('parental', options.includeSections)) {
    sections.push({
      type: 'text',
      title: 'Parental Influence',
      content: {
        fatherInfluence: parentalData.fatherInfluence?.sign,
        motherInfluence: parentalData.motherInfluence?.sign,
        combinedInfluence: parentalData.combinedInfluence?.dynamic
      }
    });
  }

  // Archetype
  const archetypeData = profile.archetypeData as any;
  if (archetypeData && shouldIncludeSection('archetype', options.includeSections)) {
    sections.push({
      type: 'text',
      title: 'Soul Archetype',
      content: {
        title: archetypeData.title,
        description: archetypeData.description,
        strengths: archetypeData.strengths,
        shadows: archetypeData.shadows
      }
    });
  }

  // Biography
  if (profile.biography && shouldIncludeSection('biography', options.includeSections)) {
    sections.push({
      type: 'text',
      title: 'Soul Biography',
      content: profile.biography
    });
  }

  return {
    title: options.customTitle || `${profile.name}'s Soul Codex`,
    sections,
    footer: options.watermark ? 'Generated by Soul Codex - Engine of the Eternal Now' : undefined,
    metadata: {
      generatedAt: new Date(),
      profileName: profile.name,
      template: options.template
    }
  };
}

/**
 * Generate compatibility PDF
 */
export function generateCompatibilityPDF(
  profile1: Profile,
  profile2: Profile,
  compatibilityData: any,
  options: PDFOptions = { template: 'compatibility', theme: 'mystical' }
): PDFTemplate {
  const sections: PDFSection[] = [];

  sections.push({
    type: 'header',
    title: 'Compatibility Analysis',
    content: {
      person1: profile1.name,
      person2: profile2.name,
      overallScore: compatibilityData.overallScore
    }
  });

  // Compatibility scores
  sections.push({
    type: 'table',
    title: 'Compatibility Scores',
    content: {
      headers: ['Category', 'Score'],
      rows: [
        ['Astrology', compatibilityData.categories?.astrology?.score || 0],
        ['Numerology', compatibilityData.categories?.numerology?.score || 0],
        ['Human Design', compatibilityData.categories?.humanDesign?.score || 0],
        ['Personality', compatibilityData.categories?.personality?.score || 0],
        ['Moral Compass', compatibilityData.categories?.moralCompass?.score || 0]
      ]
    }
  });

  // Strengths and challenges
  sections.push({
    type: 'list',
    title: 'Relationship Strengths',
    content: compatibilityData.strengths || []
  });

  sections.push({
    type: 'list',
    title: 'Growth Opportunities',
    content: compatibilityData.challenges || []
  });

  return {
    title: `${profile1.name} & ${profile2.name} - Compatibility Report`,
    sections,
    metadata: {
      generatedAt: new Date(),
      profileName: `${profile1.name} & ${profile2.name}`,
      template: 'compatibility'
    }
  };
}

/**
 * Generate transits PDF
 */
export function generateTransitsPDF(
  profile: Profile,
  transitsData: any,
  options: PDFOptions = { template: 'transits', theme: 'mystical' }
): PDFTemplate {
  const sections: PDFSection[] = [];

  sections.push({
    type: 'header',
    title: 'Current Transits',
    content: {
      profileName: profile.name,
      dateRange: transitsData.dateRange || 'Current'
    }
  });

  // Active transits
  if (transitsData.transits && transitsData.transits.length > 0) {
    sections.push({
      type: 'table',
      title: 'Active Transits',
      content: {
        headers: ['Transiting Planet', 'Aspect', 'Natal Planet', 'Intensity', 'Theme'],
        rows: transitsData.transits.map((t: any) => [
          t.planet,
          t.aspect,
          t.natalPlanet,
          t.intensity,
          t.theme
        ])
      }
    });
  }

  // Dominant theme
  sections.push({
    type: 'text',
    title: 'Dominant Theme',
    content: transitsData.dominantTheme || 'No significant transits'
  });

  return {
    title: `${profile.name}'s Transits Report`,
    sections,
    metadata: {
      generatedAt: new Date(),
      profileName: profile.name,
      template: 'transits'
    }
  };
}

/**
 * Helper functions
 */
function shouldIncludeSection(section: string, includeSections?: string[]): boolean {
  if (!includeSections) return true;
  return includeSections.includes(section);
}

function extractElements(astrologyData: any): string[] {
  const elements: string[] = [];
  if (astrologyData.sunSign) {
    const element = getElementFromSign(astrologyData.sunSign);
    if (element && !elements.includes(element)) elements.push(element);
  }
  if (astrologyData.moonSign) {
    const element = getElementFromSign(astrologyData.moonSign);
    if (element && !elements.includes(element)) elements.push(element);
  }
  if (astrologyData.risingSign) {
    const element = getElementFromSign(astrologyData.risingSign);
    if (element && !elements.includes(element)) elements.push(element);
  }
  return elements;
}

function getElementFromSign(sign: string): string | null {
  const fireSigns = ['Aries', 'Leo', 'Sagittarius'];
  const earthSigns = ['Taurus', 'Virgo', 'Capricorn'];
  const airSigns = ['Gemini', 'Libra', 'Aquarius'];
  const waterSigns = ['Cancer', 'Scorpio', 'Pisces'];
  
  if (fireSigns.includes(sign)) return 'Fire';
  if (earthSigns.includes(sign)) return 'Earth';
  if (airSigns.includes(sign)) return 'Air';
  if (waterSigns.includes(sign)) return 'Water';
  return null;
}

/**
 * Convert PDF template to actual PDF (placeholder - use pdfkit or puppeteer in production)
 */
export async function renderPDF(template: PDFTemplate): Promise<Buffer> {
  // In production, use a library like:
  // - pdfkit (Node.js)
  // - puppeteer (HTML to PDF)
  // - jsPDF (browser)
  
  // This is a placeholder that returns a mock PDF structure
  // You would implement actual PDF generation here
  
  const pdfContent = JSON.stringify(template, null, 2);
  return Buffer.from(pdfContent, 'utf-8');
}

export default {
  generateProfilePDF,
  generateCompatibilityPDF,
  generateTransitsPDF,
  renderPDF
};
